[electrum]
#MAINNET BLOCKSTREAM ELECTRUM ENDPOINT = "ssl://electrum.blockstream.info:50002"
#TESTNET BLOCKSTREAM ELECTRUM ENDPOINT = "ssl://electrum.blockstream.info:60002"
endpoint = "ssl://electrum.blockstream.info:60002"
certificate_validation = true

[group]
max_time = 300
max_size = 3

[dust]
limit = 1000

[fee]
range = 2.0

[server]
ip = "127.0.0.1"
port = "8787"

[network]
name = "testnet"
