name: Continuous Integration

on: push

jobs:
  run:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer install -d frontend
      - run: php frontend/vendor/bin/php-cs-fixer check --config frontend/.php-cs-fixer.php -v
