name: Frontend CI

on: push

jobs:
  run:
    name: Frontend Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: composer install
      - run: php vendor/bin/php-cs-fixer check -v
